apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mini-cloud-native
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/kshukshu/Mini-Cloud-Native-Platform.git
    targetRevision: HEAD
    path: k8s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
